debug: false
spring:
  datasource:
    webflash:
      url: jdbc:mysql://10.216.64.115:3306/webflash?useUnicode=true&characterEncoding=UTF8&useSSL=false
      username: cnswitch
      password: 1qaz@WSX
    test:
      url: jdbc:mysql://10.216.64.115:3306/test?useUnicode=true&characterEncoding=UTF8&useSSL=false
      username: cnswitch
      password: 1qaz@WSX
    aps:
      url: jdbc:mysql://10.216.64.115:3306/shared_aps?useUnicode=true&characterEncoding=UTF8&useSSL=false
      username: cnswitch
      password: 1qaz@WSX
  jpa:
    hibernate:
      ddl-auto: update
server:
  tomcat:
    basedir: /data/app/web-flash/runtime/tmp
